### ISSUE TITLE
Invalid number during cut

### ISSUE THREAD

**Issue by robustini** [raphaelcoeffic/horus_frk#1]
Thanks Raphael for this!
I've this error...

![immagine](https://user-images.githubusercontent.com/3864712/62003186-76f87480-b113-11e9-8f12-1b333b6124fb.png)

**Comment by raphaelcoeffic** [comment]
Seems `dd` on OS X works differently from Linux, I need to try it myself on Linux.

**Comment by raphaelcoeffic** [comment]
@robustini ok, it seems `dd` on linux does not support hexdecimal numbers. But the shell does (using `$((hexnumber))`), so I modified the doc to use that instead.
