### ISSUE TITLE
Question about the size

### ISSUE THREAD

**Issue by LapinFou** [raphaelcoeffic/horus_frk#2]
Hi @raphaelcoeffic 
Sorry to open an issue, but I guess this is the best way to ask you a question.
I'm following your procedure to extract the iXJT firmwares for the Horus X10/X12 (will be use by some friends).
Concerning the **X12S_mode2_EU_1603_frtx.bin**, the firmware size  is **0x012800**.
So it does mean I should use the CLI argument `count=$((0x12800))` instead the argument `count=72k`.
Is it correct?
Otherwise , the correct count argument would have been `count=74k`, correct?
Could give me some clarification?
In others words, it is better to used `count=$((0xXXXXX))` instead `count=XXk`, correct?

**Comment by raphaelcoeffic** [comment]
Absolutely, this is exactly the same. You can use either of 74k or 0x12800.

**Comment by LapinFou** [comment]
Thanks for your very fast answer!!!
So, it is better to always determine the firmware size then use `count=$((xx))` instead `count=xx`.
Maybe, you could add a note that firmware size can be different, couldn't you?

If you wrote this, I guess you successfully tested the generated iXJT firmware on the X10/12 radios. Correct?

And, again, thanks!!

**Comment by raphaelcoeffic** [comment]
Ok, will add the note. And yes, it has been tested and works. In case something is wrong, you can always reflash as this never overwrites the bootloader in your module.

**Comment by LapinFou** [comment]
Good to know that the module's bootloader can't be corrupted.
Thank again for this HowTo!
I don't know how you reversed the code to find the begin/end signature of the RF firmware, but well done!! 💯

**Comment by raphaelcoeffic** [comment]
I compared module firmware of other Radios and found similarities. Digging further it appears they use the same format.

**Comment by LapinFou** [comment]
Wahouuu!!
What talent!
Last question, I guess you don't make available to download the firmwares for copyright reasons, correct?

**Comment by raphaelcoeffic** [comment]
exactly, I'm not into this ;-) But feel free to do what you think is right X-P

**Comment by LapinFou** [comment]
Yep!
😄 
I think this ticket can be closed, unless you want to leave it open until you add a comment about de firmware size?!
